ClawQuestSolution/ClawQuest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ClawQuest.Data;
using ClawQuest.Models;
using System;
using System.Linq;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace ClawQuest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Owner()
        {
            var availableItems = await _context.Toys.ToListAsync();

            // Create the view model with the names and IDs of the toys
            var viewModel = new InputModel()
            {
                // This will create an array of zeros with a length equal to the number of toys
                Inputs = new int[availableItems.Count],
                ItemNames = availableItems.Select(t => t.Name).ToList(),
                ItemIds = availableItems.Select(t => t.ToyId).ToList() // Assuming you have a ToyId property in your Toy model
            };
            return View(viewModel);

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Play()
        {
            var viewModel = new PlayerView
            {

            };

            return View(viewModel);
        }

        public IActionResult Leaderboard()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClawQuestSolution/ClawQuest/Controllers/OwnerController.cs
using ClawQuest.Models;
using Microsoft.AspNetCore.Mvc;
using ClawQuest.Data;
using Microsoft.EntityFrameworkCore;

namespace ClawQuest.Controllers
{
    public class OwnerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OwnerController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> PopulateToyGrid(InputModel model)
        {
            int totalItemsInDb = _context.ClawMachineToys.ToList().Count;
            int totalItemsToAdd = model.Quantities.Where(p => p > 0).Sum();

            if (totalItemsInDb + totalItemsToAdd > 24)
            {
                TempData["ErrorMessage"] = "The total number of items cannot exceed 24.";
                return RedirectToAction("Owner", "Home");
            }

            var game = new Game();
            if(model.Quantities.Sum() > 24)
            {
                return RedirectToAction("Owner", "Home");
            }

            if (model.ItemIds.Count != model.Quantities.Count)
            {
                // Handle the error appropriately, such as adding a model error or logging.
                ModelState.AddModelError("Quantities", "The number of quantities does not match the number of item IDs.");
                // Repopulate the ItemNames for the view to use.
                model.ItemNames = await _context.Toys.Select(t => t.Name).ToListAsync();
                return RedirectToAction("Owner", "Home");
            }

            var availableToys = await _context.Toys
                                              .Where(t => model.ItemIds.Contains(t.ToyId))
                                              .ToListAsync();

            for (int i = 0; i < model.ItemIds.Count; i++)
            {
                int toyId = model.ItemIds[i];
                int quantity = model.Quantities[i];
                if (_context.ClawMachineToys.ToList().Count() < 25 && quantity > 0)
                {
                    for(int j = 0; j < quantity; j++)
                    {
                        ClawMachineToy clawMachineToy = new ClawMachineToy { ToyId = toyId };
                        _context.ClawMachineToys.Add(clawMachineToy);
                        _context.SaveChanges();
                    }
                    
                }
            }

            for (int row = 0; row < game.ToyGrid.GetLength(0); row++)
            {
                for (int col = 0; col < game.ToyGrid.GetLength(1); col++)
                {
                    if (game.ToyGrid[row, col] != null)
                    {
                        Console.WriteLine($"ToyGrid[{row}, {col}] = {game.ToyGrid[row, col].Name}");
                    }
                    else
                    {
                        Console.WriteLine($"ToyGrid[{row}, {col}] = null");
                    }
                }
            }

            return RedirectToAction("Owner", "Home");
        }
    }
}

ClawQuestSolution/ClawQuest/Controllers/PlayerController.cs
using ClawQuest.Models;
using Microsoft.AspNetCore.Mvc;
using ClawQuest.Data;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.X509Certificates;
using Microsoft.Extensions.DependencyInjection;
using System;

namespace ClawQuest.Controllers
{
    public class PlayerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayerController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult OperateClaw(PlayerView model)
        {
            var game = new Game();

            int totalCount = _context.ClawMachineToys.Count();


            Random random = new Random();
            int randomIndex = random.Next(0, totalCount);


            var randomItem = _context.ClawMachineToys
                .Skip(randomIndex)
                .FirstOrDefault();


            if (randomItem != null)
            {
                var winProbability = _context.Toys.FirstOrDefault(p => p.ToyId == randomItem.ToyId).WinProbability;
                double winPercent = random.NextDouble();
                if (winPercent >= winProbability)
                {
                    model.PrizeResult = randomItem.Toys.Name;
                    model.TriesLeft = model.TriesLeft - 1;
                    model.Score = randomItem.Toys.Points;
                }
                else
                {
                    model.PrizeResult = "Please Try Again.";
                    model.TriesLeft = model.TriesLeft - 1;
                }
            }
            TempData["PrizeResult"] = model.PrizeResult;
            TempData["TriesLeft"] = model.TriesLeft;
           //TempData["Score"] = model.Score;
            return RedirectToAction("Play", "Home");
        }
    }
}

ClawQuestSolution/ClawQuest/Views/Home/AdminLogin.cshtml
@{
    ViewData["Title"] = "Owner Login";
}
<h1>@ViewData["Title"]</h1>

<p>We'll put the method of logging in as the owner onto this page</p>

ClawQuestSolution/ClawQuest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

ClawQuestSolution/ClawQuest/Views/Home/Leaderboard.cshtml
@{
    ViewData["Title"] = "Leaderboard";
}
<h1>@ViewData["Title"]</h1>

<p>We'll put the leaderboard onto this page</p>

ClawQuestSolution/ClawQuest/Views/Home/Owner.cshtml
@model ClawQuest.Models.InputModel
@Html.ValidationSummary(true)
<partial name="_ValidationScriptsPartial" />

@{
    ViewData["Title"] = "Owner Page";
}

<h1> Owner Page</h1>
<p> This is the form to submit changes to the Claw Machine</p>
<form asp-controller ="Owner" asp-action="PopulateToyGrid" method="post">
    <div id="error-message" style="color: red; display: none;">
        You can only select a total of 24 items.
    </div>
    <div class="row">
        @for (int i = 0; i < Model.ItemNames.Count; i++)
        {
            <div class="col-md-4">
                <div class="form-group">
                    <label>@Model.ItemNames[i]</label>
                    <input type="hidden" asp-for="@Model.ItemIds[i]" />
                    <input asp-for="@Model.Quantities[i]" class="game-input form-control" type="number" min="0" max="24" />
                </div>
            </div>
        }
    </div>
    <div class="row mt-5">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">
                @TempData["ErrorMessage"]
            </div>
        }
    </div>
    <div class="col-md-4"></div>
    <button type="submit" class="form-control mt-4" style="color: #787878">Store Items</button>
    <div class="col-md-4"></div>
</form>

ClawQuestSolution/ClawQuest/Views/Home/OwnerLogin.cshtml
@{
    ViewData["Title"] = "Owner Login";
}
<h1>@ViewData["Title"]</h1>

<p>We'll put the method of logging in as the owner onto this page</p>

ClawQuestSolution/ClawQuest/Views/Home/Play.cshtml
@model ClawQuest.Models.PlayerView
@Html.ValidationSummary(true)
<partial name="_ValidationScriptsPartial" />

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Space Claw Machine</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>ClawQuest Machine</h1>
        <div class="claw-machine">
            <div class="machine-body">
                <div id="claw">
                    <div style="position:absolute;top:0;left:10px;width:40px;height:20px;background:#5b5b5b;border-radius:5px;"></div>
                    <div id="clawBar"></div>
                    <div id="clawALL">
                        <div id="clawBall"></div>
                        <div id="leftClaw"></div>
                        <div id="rightClaw"></div>
                    </div>
                </div>
            </div>
            <br />       
        </div>
        <form asp-controller="Player" asp-action="OperateClaw" method="post">
            <div id="result" class="result">Prize Result: @TempData["PrizeResult"]</div>
            <div id="tries" class="tries">Tries Left: @TempData["TriesLeft"]</div>
            <div id="score" class="score">Score: 200</div>
            <div id="claw-machine-grid" class="claw-machine-grid"></div>
            <div class="controls">
			<label for="column">Column:</label>
            <input asp-for="@Model.SelectedColumn" type="number" id="column" min="1" max="8">
			<button type="submit" onclick="operateClaw()">Operate Claw</button>
		</form>
        </div>
    <script src="script.js"></script>
</body>
</html>


    <script>
        function operateClaw() {
            const column = parseInt(document.getElementById("column").value);

            // Calculate the position for the claw based on the selected column
            const clawPosition = (column - 1) * 34; // Adjust 60 to your desired column width

            const clawElement = document.getElementById("claw");
            clawElement.style.transform = `translateX(${clawPosition}px)`;

            event.preventDefault();

            // Submit the form programmatically
            document.querySelector('form').submit();
    </script>